### ISSUE TITLE
tradefed plugin crashes when there is no data from VTS/CTS

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squadplugins#1]
```
Plugin postprocessing error: invalid file: None
Traceback (most recent call last):
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/core/tasks/__init__.py", line 216, in __call__
    self.__call_plugin__(plugin, testrun)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/core/tasks/__init__.py", line 221, in __call_plugin__
    plugin.postprocess_testrun(testrun)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/tradefed/__init__.py", line 113, in postprocess_testrun
    self.__assign_test_log(buf, failed)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/tradefed/__init__.py", line 18, in __assign_test_log
    tradefed_tree = ET.parse(buf)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 585, in parse
    source = open(source, "rb")
TypeError: invalid file: None
```

**Comment by mwasilew** [comment]
Fixed in 285ace066180533f00cb33808a390e9565295973
