### ISSUE TITLE
Error in tradefed file saving

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squadplugins#18]
```
Plugin postprocessing error: 'NoneType' object has no attribute 'contents'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/squad/ci/models.py", line 144, in __postprocess_testjob__
    plugin.postprocess_testjob(test_job)
  File "/usr/local/lib/python3.7/dist-packages/tradefed/__init__.py", line 434, in postprocess_testjob
    self._extract_cts_results(results.test_results.contents, testjob.testrun, test_definition['name'])
AttributeError: 'NoneType' object has no attribute 'contents'
```

**Comment by chaws** [comment]
Fixed in https://github.com/Linaro/squadplugins/pull/20
