### ISSUE TITLE
suite_node is sometimes None

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squadplugins#2]
```
Traceback (most recent call last):
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/core/tasks/__init__.py", line 216, in __call__
    self.__call_plugin__(plugin, testrun)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/core/tasks/__init__.py", line 221, in __call_plugin__
    plugin.postprocess_testrun(testrun)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/tradefed/__init__.py", line 128, in postprocess_testrun
    self.__assign_test_log(buf, failed)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/tradefed/__init__.py", line 38, in __assign_test_log
    log_node = suite_node.find('.//Test[@name="%s"]' % test_name)
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by mwasilew** [comment]
Fixed in 4a7dac18242f2bb8d7dc43d09c7b85452861bbf8
