### ISSUE TITLE
Tradefed attachments fail sometimes

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squadplugins#5]
```
Plugin postprocessing error: 'NoneType' object has no attribute 'test_results'
Traceback (most recent call last):
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ci/models.py", line 130, in __postprocess_testjob__
    plugin.postprocess_testjob(test_job)
  File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/tradefed/__init__.py", line 170, in postprocess_testjob
    self.__assign_test_log(results.test_results.contents, failed)
AttributeError: 'NoneType' object has no attribute 'test_results'
```

**Comment by chaws** [comment]
@mwasilew does still happen? I don't recall seeing this for a long time

**Comment by mwasilew** [comment]
I think I fixed it. When did this error happen?

**Comment by chaws** [comment]
You reported it in Nov 7 2018. It's been a while since I don't see this error

**Comment by mwasilew** [comment]
I think it's safe to close it now.
